openapi: '3.0.3'
info:
  title: API for SNS
  version: 1.0.0
tags:
  - name: post
    description: 投稿・TL 関連
  - name: user
    description: 自分でないユーザーに対する操作
  - name: settings
    description: アカウントの設定
paths:
  /posts:
    post:
      tags:
        - post
      summary: ポストする
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      requestBody:
        description: ポストの内容
        content:
          application/json:
            schema:
              type: string
              description: ポストの本文
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/post'
  /posts/{postId}:
    get:
      tags:
        - post
      summary: 一つのポストを取得する
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: string
            description: postId
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/post'
    delete:
      tags:
        - post
      summary: ポストを削除する
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: string
            description: postId
      responses:
        '204':
          description: no content
  /posts/{postId}/like:
    get:
      tags:
        - post
      summary: ポストにいいねする
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: string
            description: postId
      responses:
        '204':
          description: no content
  /posts/{postId}/unlike:
    get:
      tags:
        - post
      summary: ポストへのいいねを取り消す
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: string
            description: postId
      responses:
        '204':
          description: no content
  /timeline:
    get:
      tags:
        - post
      summary: タイムラインを取得する
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/post'
  /user/{userId}:
    get:
      tags:
        - user
      summary: ユーザーのプロフィールを取得する
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            description: userId
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
  /user/{userId}/icon:
    get:
      tags:
        - user
      summary: ユーザーのアイコンを取得する
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            description: userId
      responses:
        '200':
          description: successful operation
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
  /user/{userId}/bgimage:
    get:
      tags:
        - user
      summary: ユーザーの背景画像を取得する
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            description: userId
      responses:
        '200':
          description: successful operation
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
  /user/{userId}/posts:
    get:
      tags:
        - user
      summary: ユーザーのポスト一覧を取得する
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            description: userId
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/post'
  /user/{userId}/follow:
    get:
      tags:
        - user
      summary: ユーザーをフォローする
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            description: userId
      responses:
        '204':
          description: no content
  /user/{userId}/unfollow:
    get:
      tags:
        - user
      summary: ユーザーのフォローを外す
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            description: userId
      responses:
        '204':
          description: no content
  /user/{userId}/follower:
    get:
      tags:
        - user
      summary: ユーザーのフォロワーを取得する
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            description: userId
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'
  /settings/profile:
    put:
      tags:
        - settings
      summary: プロフィールを設定する
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      requestBody:
        description: プロフィールの内容
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
  /settings/profile/icon:
    put:
      tags:
        - settings
      summary: アイコンを設定する
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      requestBody:
        description: アイコン画像
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '204':
          description: no content
  /settings/profile/bgImage:
    put:
      tags:
        - settings
      summary: 背景画像を設定する
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      requestBody:
        description: 背景画像
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '204':
          description: no content


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    post:
      type: object
      properties:
        postId:
          type: string
        poster:
          type: object
          properties:
            userId:
              type: string
            userName:
              type: string
        likes:
          type: integer
        date:
          type: string
          format: date-time
        content:
          type: string
    user:
      type: object
      properties:
        userId:
          type: string
        userName:
          type: string
        biography:
          type: string
        