openapi: '3.0.3'
info:
  title: API for SNS
  version: 1.0.0
tags:
  - name: post
    description: 投稿・TL 関連
  - name: user
    description: 自分でないユーザーに対する操作
  - name: follows
    description: フォロー関連
  - name: settings
    description: アカウントの設定
paths:
  /api/posts:
    post:
      tags:
        - post
      summary: ポストする
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      requestBody:
        description: ポストの内容
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  description: ポストの本文
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/post'
  /api/posts/{postId}:
    get:
      tags:
        - post
      summary: 一つのポストを取得する
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: string
            description: postId
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/post'
    delete:
      tags:
        - post
      summary: ポストを削除する
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: string
            description: postId
      responses:
        '204':
          description: no content
  /api/posts/{postId}/likes:
    get:
      tags:
        - post
      summary: ポストにいいねした人を取得する
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: string
            description: postId
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'
  /api/posts/like:
    put:
      tags:
        - post
      summary: ポストにいいねする
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      requestBody:
        description: いいねしたいポスト
        content:
          application/json:
            schema:
              type: object
              properties:
                postId:
                  type: string
                  description: いいねしたいポストの id
      responses:
        '204':
          description: no content
  /api/posts/unlike:
    put:
      tags:
        - post
      summary: ポストへのいいねを取り消す
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      requestBody:
        description: いいねを取り消したいポスト
        content:
          application/json:
            schema:
              type: object
              properties:
                postId:
                  type: string
                  description: いいねを取り消したいポストの id
      responses:
        '204':
          description: no content
  /api/timeline:
    get:
      tags:
        - post
      summary: タイムラインを取得する
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/post'
  /api/users/{userName}:
    get:
      tags:
        - user
      summary: ユーザーのプロフィールを取得する
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: userName
          required: true
          schema:
            type: string
            description: userName
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
  /api/users/{userName}/icon:
    get:
      tags:
        - user
      summary: ユーザーのアイコンを取得する
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: userName
          required: true
          schema:
            type: string
            description: userName
      responses:
        '200':
          description: successful operation
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
  /api/users/{userName}/bgImage:
    get:
      tags:
        - user
      summary: ユーザーの背景画像を取得する
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: userName
          required: true
          schema:
            type: string
            description: userName
      responses:
        '200':
          description: successful operation
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
  /api/users/{userName}/posts:
    get:
      tags:
        - user
      summary: ユーザーのポスト一覧を取得する
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: userName
          required: true
          schema:
            type: string
            description: userName
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/post'
  /api/users/{userName}/mutuals:
    get:
      tags:
        - user
      summary: ユーザーとの相互フォローを取得する
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: userName
          required: true
          schema:
            type: string
            description: userName
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'
  /api/follows/follow:
    put:
      tags:
        - follows
      summary: ユーザーをフォローする
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      requestBody:
        description: フォローしたいユーザー
        content:
          application/json:
            schema:
              type: object
              properties:
                userName:
                  type: string
                  description: フォローしたいユーザーのユーザー名
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  followingUserName:
                    type: string
  /api/follows/unfollow:
    put:
      tags:
        - follows
      summary: ユーザーのフォローを外す
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      requestBody:
        description: フォロー解除したいユーザー
        content:
          application/json:
            schema:
              type: object
              properties:
                userName:
                  type: string
                  description: フォロー解除したいユーザーのユーザー名
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  unfollowingUserName:
                    type: string
  /api/follows/requests:
    get:
      tags:
        - follows
      summary: フォローリクエストを取得する
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'
  /api/follows/reject:
    put:
      tags:
        - follows
      summary: フォローリクエストを拒否する
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      requestBody:
        description: フォローリクエストを拒否したいユーザー
        content:
          application/json:
            schema:
              type: object
              properties:
                userName:
                  type: string
                  description: フォローリクエストを拒否したいユーザーのユーザー名
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  rejectedUserName:
                    type: string
  /api/settings/profile:
    put:
      tags:
        - settings
      summary: プロフィールを設定する
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      requestBody:
        description: プロフィールの内容
        content:
          application/json:
            schema:
              type: object
              properties:
                userName:
                  type: string
                displayName:
                  type: string
                biography:
                  type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  userName:
                    type: string
                  displayName:
                    type: string
                  biography:
                    type: string
  /api/settings/profile/icon:
    put:
      tags:
        - settings
      summary: アイコンを設定する
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      requestBody:
        description: アイコン画像
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '204':
          description: no content
  /api/settings/profile/bgImage:
    put:
      tags:
        - settings
      summary: 背景画像を設定する
      description: Authorization ヘッダーを必要とします
      security:
        - bearerAuth: []
      requestBody:
        description: 背景画像
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '204':
          description: no content
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    post:
      type: object
      properties:
        postId:
          type: string
        poster:
          type: object
          properties:
            userName:
              type: string
            displayName:
              type: string
        likes:
          type: integer
        liked:
          type: boolean
        comments:
          type: integer
        content:
          type: string
        createdAt:
          type: string
          format: date-time
    postDetail:
      type: object
      properties:
        postId:
          type: string
        poster:
          type: object
          properties:
            userName:
              type: string
            displayName:
              type: string
        likes:
          type: integer
        liked:
          type: boolean
        comments:
          type: integer
        content:
          type: string
        createdAt:
          type: string
          format: date-time
        conversations:
          type: array
          items:
            type: object
            properties:
              user:
                type: object
                properties:
                  userName:
                    type: string
                  displayName:
                    type: string
              replies:
                type: array
                items:
                  type: object
                  properties:
                    user:
                      type: object
                      properties:
                        userName:
                          type: string
                        displayName:
                          type: string
                    content:
                      type: string
                    createdAt:
                      type: string
                      format: date-time
              content:
                type: string
              createdAt:
                type: string
                format: date-time
    user:
      type: object
      properties:
        userName:
          type: string
        displayName:
          type: string
        biography:
          type: string
        createdAt:
          type: string
          format: date-time
        followingStatus:
          type: string